apiVersion: v1
kind: Service
metadata:
  name: gptgov-backend-service-entry
spec:
  selector:
    app: govgpt
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 5050
      targetPort: 5050
  type: LoadBalancer
