apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: govgpt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Port on which the frontend container is running
  type: LoadBalancer
