apiVersion: v1
kind: Pod
metadata:
  name: govgpt
  labels:
    app: govgpt
spec:
  containers:
    - name: govgpt-frontend
      image: us-central1-docker.pkg.dev/govgpt-kl/gov-gpt/govgpt-frontend:v0.0.2
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: frontend-configmap
    - name: govgpt-backend-core
      image: us-central1-docker.pkg.dev/govgpt-kl/gov-gpt/govgpt-backend-core:v0.1
      ports:
        - containerPort: 5050
      envFrom:
        - configMapRef:
            name: backend-core-configmap
